### ISSUE TITLE
When moving item to other case, change location to corresponding location in target case

### ISSUE THREAD

**Issue by saerdnaer** [voc/wink#11]
When moving item to other case, change location to corresponding location in target case, including subitems.

E.g. when moving  "Konverter SDI → HDMI" from case 5 to case 6, set location from item 962 "Meshbag HDMI (grün)" to item 1052 "Meshbag HDMI (grün)"

Same for subitem Netzteil.

**Comment by meise** [comment]
Duplicate of #9
